# Generated by Django 3.0.7 on 2020-08-22 13:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('domain', models.TextField(unique=True)),
                ('creator', models.TextField(blank=True)),
                ('takedown', models.BooleanField(default=False)),
                ('reason', models.TextField(default='')),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.TextField(blank=True)),
                ('dept', models.TextField(blank=True)),
                ('number', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('title', models.TextField(blank=True)),
                ('semester', models.TextField(blank=True)),
                ('hidden', models.BooleanField(default=True)),
                ('year', models.TextField(blank=True)),
                ('syllabus', models.FileField(blank=True, upload_to='test/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabiShare.School')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('suggestion_text', models.TextField()),
                ('github_issue', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('hide_name', models.BooleanField(default=False)),
                ('confirmations_sent', models.SmallIntegerField(default=0)),
                ('saved', models.ManyToManyField(to='syllabiShare.Submission')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabiShare.School')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
