# Generated by Django 2.1.5 on 2020-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0002_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='domain',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
