# Generated by Django 2.1.5 on 2020-05-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0003_auto_20200519_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='add_date',
        ),
        migrations.AddField(
            model_name='submission',
            name='syllabus',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='upvotes',
            field=models.IntegerField(default=1),
        ),
    ]
