# Generated by Django 2.1.5 on 2020-05-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0004_auto_20200519_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='syllabus',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
