# Generated by Django 2.1.5 on 2020-05-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0005_auto_20200520_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='poster',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
