# Generated by Django 3.0.6 on 2020-05-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0009_auto_20200521_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='dept',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='course',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='prof',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='school',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.TextField(blank=True),
        ),
    ]
