# Generated by Django 3.0.6 on 2020-05-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0010_auto_20200522_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='github_issue',
            field=models.TextField(default=''),
        ),
    ]
