# Generated by Django 3.0.6 on 2020-05-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0011_suggestion_github_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='reason',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='school',
            name='takedown',
            field=models.BooleanField(default=False),
        ),
    ]
