# Generated by Django 2.2.5 on 2020-05-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0012_auto_20200525_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
