# Generated by Django 3.0.6 on 2020-05-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0012_auto_20200525_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='semester',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='year',
            field=models.TextField(blank=True),
        ),
    ]
