# Generated by Django 2.2.5 on 2020-05-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0013_auto_20200526_2337'),
        ('syllabiShare', '0013_submission_title'),
    ]

    operations = [
    ]
