# Generated by Django 3.0.6 on 2020-06-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0014_merge_20200528_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='hidden',
            field=models.TextField(default=True),
        ),
    ]
