# Generated by Django 3.0.6 on 2020-06-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0015_submission_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
