# Generated by Django 3.0.6 on 2020-06-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0015_submission_hidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='poster',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school',
            new_name='name',
        ),
    ]
