# Generated by Django 3.0.6 on 2020-06-01 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0016_auto_20200601_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='course',
        ),
        migrations.AlterField(
            model_name='submission',
            name='number',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
