# Generated by Django 3.0.6 on 2020-06-02 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0017_auto_20200601_1623'),
        ('syllabiShare', '0015_submission_hidden'),
    ]

    operations = [
    ]
