# Generated by Django 3.0.6 on 2020-06-02 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0018_populate_school_fk_for_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='school',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='school_fk_temp',
            new_name='school',
        ),
    ]
