# Generated by Django 3.0.6 on 2020-06-07 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0016_auto_20200606_1401'),
        ('syllabiShare', '0018_merge_20200601_2232'),
    ]

    operations = [
    ]
