# Generated by Django 3.0.6 on 2020-06-02 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0019_submission_remove_school_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabiShare.School'),
        ),
    ]
