# Generated by Django 3.0.6 on 2020-06-02 03:55
from django.conf import settings
from django.db import migrations


def populate_user_fk_for_submission(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    Submission = apps.get_model('syllabiShare', 'Submission')
    for submission in Submission.objects.all():
        submission.user_fk_temp = User.objects.get(username=submission.user)
        submission.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syllabiShare', '0021_submission_user_fk_temp'),
    ]

    operations = [
        migrations.RunPython(populate_user_fk_for_submission)
    ]
