# Generated by Django 3.0.6 on 2020-06-02 16:22
from django.conf import settings
from django.db import migrations


def link_profile_to_user(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    UserProfile = apps.get_model('syllabiShare', 'UserProfile')
    School = apps.get_model('syllabiShare', 'School')
    for user in User.objects.all():
        start = user.email.index('@') + 1
        end = user.email.index('.edu')
        domain = user.email[start:end]
        profile = UserProfile(user=user, school=School.objects.get(domain=domain))
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syllabiShare', '0025_userprofile'),
    ]

    operations = [
        migrations.RunPython(link_profile_to_user)
    ]
