# Generated by Django 3.0.6 on 2020-06-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0026_link_profile_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='uploads',
        ),
    ]
