# Generated by Django 3.0.6 on 2020-06-08 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0028_auto_20200603_1150'),
        ('syllabiShare', '0019_merge_20200607_1535'),
    ]

    operations = [
    ]
