# Generated by Django 3.0.6 on 2020-06-09 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0030_auto_20200608_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabiShare.School'),
        ),
    ]
