# Generated by Django 3.0.6 on 2020-06-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0032_userprofile_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='upvotes',
        ),
    ]
