# Generated by Django 3.0.7 on 2020-06-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabiShare', '0033_remove_submission_upvotes'),
        ('syllabiShare', '0032_userprofile_confirmations_sent'),
    ]

    operations = [
    ]
